export const BASE_URL = "https://localhost:44396/api";

// export const DEFAULT_CATEGORIES: Category[] = [
//   {
//     id: "1",
//     name: "جلود",
//     icon: "Layers",
//     color: "#8b4513",
//     subcategories: ["طبيعي", "صناعي", "ملون", "محبب", "لامع", "شامواه"],
//   },
//   {
//     id: "2",
//     name: "لاصق",
//     icon: "Droplets",
//     color: "#2196f3",
//     subcategories: ["مائي", "لاصق حراري", "صناعي", "أسمنت تلامسي", "إيبوكسي"],
//   },
//   {
//     id: "3",
//     name: "إكسسوارات",
//     icon: "Package",
//     color: "#ff9800",
//     subcategories: ["أزرار", "سوستة", "أبزيم", "معدّات", "مسامير", "كباسات"],
//   },
//   {
//     id: "4",
//     name: "صناديق معبأة",
//     icon: "Box",
//     color: "#9c27b0",
//     subcategories: [
//       "عدة أدوات",
//       "مستلزمات مختلطة",
//       "مجموعات مبتدئين",
//       "مجموعات محترفين",
//     ],
//   },
// ];

// export const INITIAL_PRODUCTS: Product[] = [
//   {
//     id: "1",
//     name: "جلد بقري فاخر",
//     type: "leather",
//     category: "جلود",
//     subcategory: "طبيعي",
//     unit: "متر",
//     price: 45.0,
//     stock: 150,
//     minStock: 20,
//     description: "لفة جلد بقري طبيعي عالي الجودة من إيطاليا",
//   },
//   {
//     id: "2",
//     name: "جلد شامواه بني",
//     type: "leather",
//     category: "جلود",
//     subcategory: "شامواه",
//     unit: "متر",
//     price: 38.5,
//     stock: 85,
//     minStock: 15,
//     description: "جلد شامواه بني ناعم للمنتجات الفاخرة",
//   },
//   {
//     id: "3",
//     name: "عدة أدوات الجلد",
//     type: "accessory",
//     category: "أدوات",
//     subcategory: "عدة كاملة",
//     unit: "قطعة",
//     price: 120.0,
//     stock: 25,
//     minStock: 5,
//     description: "مجموعة كاملة من 12 أداة للعمل بالجلد",
//   },
//   {
//     id: "4",
//     name: "أبازيم نحاسية",
//     type: "accessory",
//     category: "إكسسوارات",
//     subcategory: "أبزيم",
//     unit: "قطعة",
//     price: 15.75,
//     stock: 200,
//     minStock: 50,
//     description: "أبازيم نحاسية عالية الجودة بمقاسات مختلفة",
//   },
//   {
//     id: "5",
//     name: "جلد لامع أسود",
//     type: "leather",
//     category: "جلود",
//     subcategory: "لامع",
//     unit: "متر",
//     price: 52.0,
//     stock: 8,
//     minStock: 10,
//     description: "جلد أسود لامع للمحافظ والأحزمة",
//   },
//   {
//     id: "6",
//     name: "لاصق صناعي للجلود",
//     type: "accessory",
//     category: "مواد مساعدة",
//     subcategory: "لاصق",
//     unit: "لتر",
//     price: 28.5,
//     stock: 45,
//     minStock: 10,
//     description: "لاصق قوي خاص بأعمال الجلود",
//   },
//   {
//     id: "7",
//     name: "سوستة معدنية",
//     type: "accessory",
//     category: "إكسسوارات",
//     subcategory: "سوستة",
//     unit: "قطعة",
//     price: 22.0,
//     stock: 120,
//     minStock: 30,
//     description: "سوستة معدنية بأطوال مختلفة",
//   },
//   {
//     id: "8",
//     name: "جلد نعام طبيعي",
//     type: "leather",
//     category: "جلود",
//     subcategory: "فاخر",
//     unit: "متر",
//     price: 85.0,
//     stock: 12,
//     minStock: 3,
//     description: "جلد نعام طبيعي نادر للتصاميم الفاخرة",
//   },
//   {
//     id: "9",
//     name: "خيوط جلدية",
//     type: "accessory",
//     category: "مواد مساعدة",
//     subcategory: "خيوط",
//     unit: "رول",
//     price: 18.0,
//     stock: 65,
//     minStock: 15,
//     description: "خيوط جلدية متينة بألوان مختلفة",
//   },
//   {
//     id: "10",
//     name: "جلد تمساح",
//     type: "leather",
//     category: "جلود",
//     subcategory: "فاخر",
//     unit: "متر",
//     price: 120.0,
//     stock: 5,
//     minStock: 2,
//     description: "جلد تمساح أصلي للتصاميم الفاخرة",
//   },
//   {
//     id: "11",
//     name: "مقص جلد صناعي",
//     type: "accessory",
//     category: "أدوات",
//     subcategory: "مقص",
//     unit: "قطعة",
//     price: 45.0,
//     stock: 18,
//     minStock: 5,
//     description: "مقص خاص بقص الجلود بمقاسات مختلفة",
//   },
//   {
//     id: "12",
//     name: "جلد مدبوغ نباتي",
//     type: "leather",
//     category: "جلود",
//     subcategory: "طبيعي",
//     unit: "متر",
//     price: 48.0,
//     stock: 30,
//     minStock: 10,
//     description: "جلد مدبوغ بالطرق النباتية الصديقة للبيئة",
//   },
//   {
//     id: "13",
//     name: "أحزمة جاهزة",
//     type: "leather",
//     category: "منتجات نهائية",
//     subcategory: "حزام",
//     unit: "قطعة",
//     price: 75.0,
//     stock: 40,
//     minStock: 10,
//     description: "أحزمة جلدية جاهزة بمقاسات مختلفة",
//   },
//   {
//     id: "14",
//     name: "مسامير تثبيت",
//     type: "accessory",
//     category: "إكسسوارات",
//     subcategory: "مسامير",
//     unit: "علبة",
//     price: 12.0,
//     stock: 85,
//     minStock: 20,
//     description: "مسامير تثبيت للجلود بمقاسات مختلفة",
//   },
//   {
//     id: "15",
//     name: "جلد غزال",
//     type: "leather",
//     category: "جلود",
//     subcategory: "ناعم",
//     unit: "متر",
//     price: 65.0,
//     stock: 15,
//     minStock: 5,
//     description: "جلد غزال ناعم للمنتجات الحساسة",
//   },
//   {
//     id: "16",
//     name: "علبة أدوات جلد",
//     type: "accessory",
//     category: "أدوات",
//     subcategory: "علبة",
//     unit: "قطعة",
//     price: 90.0,
//     stock: 12,
//     minStock: 3,
//     description: "علبة حفظ أدوات الجلد المهنية",
//   },
//   {
//     id: "17",
//     name: "جلد مقوى",
//     type: "leather",
//     category: "جلود",
//     subcategory: "صناعي",
//     unit: "متر",
//     price: 32.0,
//     stock: 50,
//     minStock: 15,
//     description: "جلد مقوى للاستخدامات الشاقة",
//   },
//   {
//     id: "18",
//     name: "محفظة جلدية",
//     type: "leather",
//     category: "منتجات نهائية",
//     subcategory: "محفظة",
//     unit: "قطعة",
//     price: 110.0,
//     stock: 25,
//     minStock: 5,
//     description: "محفظة جلدية فاخرة بتصميم عصري",
//   },
//   {
//     id: "19",
//     name: "جلد ملون",
//     type: "leather",
//     category: "جلود",
//     subcategory: "ملون",
//     unit: "متر",
//     price: 42.0,
//     stock: 35,
//     minStock: 10,
//     description: "جلد ملون بألوان متنوعة",
//   },
//   {
//     id: "20",
//     name: "طقم إبر خياطة",
//     type: "box",
//     category: "أدوات",
//     subcategory: "إبر",
//     unit: "طقم",
//     price: 25.0,
//     stock: 40,
//     minStock: 10,
//     description: "طقم إبر خياطة الجلود الاحترافية",
//   },
// ];
